name: Reusable Release Icon Pack

on:
  workflow_call:
    inputs:
      base_tag:
        required: true
        type: string
      icon_pack_id:
        required: true
        type: string

permissions:
  contents: write
  id-token: write

jobs:
  build_and_release:
    name: Build and Release ${{ inputs.icon_pack_id }}
    runs-on: self-hosted
    container:
      image: python:3.12-slim
      options: --user root

    steps:
      - name: Install dependencies
        run: |
          apt-get update
          apt-get install -y curl git zip
          rm -rf /var/lib/apt/lists/*

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install uv
        run: |
          pip install uv
          uv pip install --system -e .

      - name: Render ${{ inputs.icon_pack_id }}
        run: python -m renderer "${{ inputs.icon_pack_id }}"

      - name: Create new tag
        run: |
          new_tag="${{ inputs.base_tag }}-${{ inputs.icon_pack_id }}"
          git tag -a "$new_tag" -m "Release $new_tag"
          git push origin "$new_tag"

      - name: Publish Release
        uses: softprops/action-gh-release@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          RELEASE_URL: https://github.com/${{ github.repository }}/releases/download/${{ inputs.base_tag }}-${{ inputs.icon_pack_id }}
        with:
          name: "${{ inputs.icon_pack_id }} ${{ inputs.base_tag }}"
          tag_name: "${{ inputs.base_tag }}-${{ inputs.icon_pack_id }}"
          body: |
            ### ðŸŽ¨ Icon Pack Variants

            <table>
              <tr>
                <td>
                  <img src="${{ env.RELEASE_URL }}/${{ inputs.icon_pack_id }}-white-transparent-thumb-16x9.jpg"><br/>
                  <a href="${{ env.RELEASE_URL }}/${{ inputs.icon_pack_id }}-white-transparent.streamDeckIconPack">Stream Deck</a><br/>
                  <a href="${{ env.RELEASE_URL }}/${{ inputs.icon_pack_id }}-white-transparent.SDICON">Stream Dock</a>
                </td>
                <td>
                  <img src="${{ env.RELEASE_URL }}/${{ inputs.icon_pack_id }}-white-thumb-16x9.jpg"><br/>
                  <a href="${{ env.RELEASE_URL }}/${{ inputs.icon_pack_id }}-white.streamDeckIconPack">Stream Deck</a><br/>
                  <a href="${{ env.RELEASE_URL }}/${{ inputs.icon_pack_id }}-white.SDICON">Stream Dock</a>
                </td>
                <td>
                  <img src="${{ env.RELEASE_URL }}/${{ inputs.icon_pack_id }}-deep-blue-transparent-thumb-16x9.jpg"><br/>
                  <a href="${{ env.RELEASE_URL }}/${{ inputs.icon_pack_id }}-deep-blue-transparent.streamDeckIconPack">Stream Deck</a><br/>
                  <a href="${{ env.RELEASE_URL }}/${{ inputs.icon_pack_id }}-deep-blue-transparent.SDICON">Stream Dock</a>
                </td>
                <td>
                  <img src="${{ env.RELEASE_URL }}/${{ inputs.icon_pack_id }}-deep-blue-thumb-16x9.jpg"><br/>
                  <a href="${{ env.RELEASE_URL }}/${{ inputs.icon_pack_id }}-deep-blue.streamDeckIconPack">Stream Deck</a><br/>
                  <a href="${{ env.RELEASE_URL }}/${{ inputs.icon_pack_id }}-deep-blue.SDICON">Stream Dock</a>
                </td>
              </tr>
            
              <tr>
                <td>
                  <img src="${{ env.RELEASE_URL }}/${{ inputs.icon_pack_id }}-emerald-green-transparent-thumb-16x9.jpg"><br/>
                  <a href="${{ env.RELEASE_URL }}/${{ inputs.icon_pack_id }}-emerald-green-transparent.streamDeckIconPack">Stream Deck</a><br/>
                  <a href="${{ env.RELEASE_URL }}/${{ inputs.icon_pack_id }}-emerald-green-transparent.SDICON">Stream Dock</a>
                </td>
                <td>
                  <img src="${{ env.RELEASE_URL }}/${{ inputs.icon_pack_id }}-emerald-green-thumb-16x9.jpg"><br/>
                  <a href="${{ env.RELEASE_URL }}/${{ inputs.icon_pack_id }}-emerald-green.streamDeckIconPack">Stream Deck</a><br/>
                  <a href="${{ env.RELEASE_URL }}/${{ inputs.icon_pack_id }}-emerald-green.SDICON">Stream Dock</a>
                </td>
                <td>
                  <img src="${{ env.RELEASE_URL }}/${{ inputs.icon_pack_id }}-warm-amber-transparent-thumb-16x9.jpg"><br/>
                  <a href="${{ env.RELEASE_URL }}/${{ inputs.icon_pack_id }}-warm-amber-transparent.streamDeckIconPack">Stream Deck</a><br/>
                  <a href="${{ env.RELEASE_URL }}/${{ inputs.icon_pack_id }}-warm-amber-transparent.SDICON">Stream Dock</a>
                </td>
                <td>
                  <img src="${{ env.RELEASE_URL }}/${{ inputs.icon_pack_id }}-warm-amber-thumb-16x9.jpg"><br/>
                  <a href="${{ env.RELEASE_URL }}/${{ inputs.icon_pack_id }}-warm-amber.streamDeckIconPack">Stream Deck</a><br/>
                  <a href="${{ env.RELEASE_URL }}/${{ inputs.icon_pack_id }}-warm-amber.SDICON">Stream Dock</a>
                </td>
              </tr>
            
              <tr>
                <td>
                  <img src="${{ env.RELEASE_URL }}/${{ inputs.icon_pack_id }}-crimson-red-transparent-thumb-16x9.jpg"><br/>
                  <a href="${{ env.RELEASE_URL }}/${{ inputs.icon_pack_id }}-crimson-red-transparent.streamDeckIconPack">Stream Deck</a><br/>
                  <a href="${{ env.RELEASE_URL }}/${{ inputs.icon_pack_id }}-crimson-red-transparent.SDICON">Stream Dock</a>
                </td>
                <td>
                  <img src="${{ env.RELEASE_URL }}/${{ inputs.icon_pack_id }}-crimson-red-thumb-16x9.jpg"><br/>
                  <a href="${{ env.RELEASE_URL }}/${{ inputs.icon_pack_id }}-crimson-red.streamDeckIconPack">Stream Deck</a><br/>
                  <a href="${{ env.RELEASE_URL }}/${{ inputs.icon_pack_id }}-crimson-red.SDICON">Stream Dock</a>
                </td>
                <td>
                  <img src="${{ env.RELEASE_URL }}/${{ inputs.icon_pack_id }}-royal-purple-transparent-thumb-16x9.jpg"><br/>
                  <a href="${{ env.RELEASE_URL }}/${{ inputs.icon_pack_id }}-royal-purple-transparent.streamDeckIconPack">Stream Deck</a><br/>
                  <a href="${{ env.RELEASE_URL }}/${{ inputs.icon_pack_id }}-royal-purple-transparent.SDICON">Stream Dock</a>
                </td>
                <td>
                  <img src="${{ env.RELEASE_URL }}/${{ inputs.icon_pack_id }}-royal-purple-thumb-16x9.jpg"><br/>
                  <a href="${{ env.RELEASE_URL }}/${{ inputs.icon_pack_id }}-royal-purple.streamDeckIconPack">Stream Deck</a><br/>
                  <a href="${{ env.RELEASE_URL }}/${{ inputs.icon_pack_id }}-royal-purple.SDICON">Stream Dock</a>
                </td>
              </tr>
            </table>
          files: |
            build/*.streamDeckIconPack
            build/*.SDICON
            build/*-thumb-16x9.jpg
          make_latest: false
